// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnC440wsayOOyRVlIQIxh-6uicsQdl3u4',
    appId: '1:372902399432:web:c1d0b02704d5a6974f44fd',
    messagingSenderId: '372902399432',
    projectId: 'crypto-wallet-30eb8',
    authDomain: 'crypto-wallet-30eb8.firebaseapp.com',
    storageBucket: 'crypto-wallet-30eb8.appspot.com',
    measurementId: 'G-MVGHQPM227',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiBmaPjGSODLgPfpkFYRsdbRV5A5DyveM',
    appId: '1:372902399432:android:3a01a9bb017798ac4f44fd',
    messagingSenderId: '372902399432',
    projectId: 'crypto-wallet-30eb8',
    storageBucket: 'crypto-wallet-30eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-hBbvcwXjcEbyE0u0lMXUjOWOj8tCIv8',
    appId: '1:372902399432:ios:b7a84bb57b7482f34f44fd',
    messagingSenderId: '372902399432',
    projectId: 'crypto-wallet-30eb8',
    storageBucket: 'crypto-wallet-30eb8.appspot.com',
    iosClientId: '372902399432-8bk5d8baidtmfj6h7bht1rh6lquhb7s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-hBbvcwXjcEbyE0u0lMXUjOWOj8tCIv8',
    appId: '1:372902399432:ios:b7a84bb57b7482f34f44fd',
    messagingSenderId: '372902399432',
    projectId: 'crypto-wallet-30eb8',
    storageBucket: 'crypto-wallet-30eb8.appspot.com',
    iosClientId: '372902399432-8bk5d8baidtmfj6h7bht1rh6lquhb7s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoWallet',
  );
}
